
export type Course = {
  id: string; // Add an ID field
  title: string;
  resourceUrl: string;
  type: 'video' | 'course' | 'webpage' | 'playlist' | 'info';
  isFree: boolean;
  imageId: string;
  category: string; // Add category to each course
};
// adding more field 
export type CourseCategory = {
  name: string;
  courses: Course[];
};

export const courseData: CourseCategory[] = [
  {
    name: 'Languages',
    courses: [
      {
        id: 'cpp-video',
        title: 'C++',
        resourceUrl: 'https://youtu.be/e7sAf4SbS_g',
        type: 'video',
        isFree: true,
        imageId: 'cpp',
        category: 'Languages',
      },
      {
        id: 'cpp-dsa',
        title: 'C++ DSA Course',
        resourceUrl: 'https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2',
        type: 'course',
        isFree: true,
        imageId: 'cpp',
        category: 'Languages',
      },
      {
        id: 'cpp-webpage',
        title: 'Learn C++',
        resourceUrl: 'https://www.learncpp.com/#table-of-contents',
        type: 'webpage',
        isFree: true,
        imageId: 'cpp',
        category: 'Languages',
      },
      {
        id: 'java-playlist',
        title: 'Java Tutorials For Beginners',
        resourceUrl: 'https://www.youtube.com/watch?v=UmnCZ7-9yDY&list=PLu0W_9lII9agS67Uits0UnJyrYiXhDS6q',
        type: 'playlist',
        isFree: true,
        imageId: 'java',
        category: 'Languages',
      },
      {
        id: 'python-video',
        title: 'Python for Beginners',
        resourceUrl: 'https://youtu.be/K5KVEU3aaeQ',
        type: 'video',
        isFree: true,
        imageId: 'python',
        category: 'Languages',
      },
      {
        id: 'python-course-paid',
        title: 'Complete Python Bootcamp',
        resourceUrl: 'https://www.udemy.com/share/103IHM/',
        type: 'course',
        isFree: false,
        imageId: 'python',
        category: 'Languages',
      },
      {
        id: 'html-video',
        title: 'HTML Tutorial for Beginners',
        resourceUrl: 'https://www.youtube.com/watch?v=HcOc7P5BMi4',
        type: 'video',
        isFree: true,
        imageId: 'html',
        category: 'Languages',
      },
      {
        id: 'css-video',
        title: 'CSS Tutorial for Beginners',
        resourceUrl: 'https://www.youtube.com/watch?v=ESnrn1kAD4E',
        type: 'video',
        isFree: true,
        imageId: 'css',
        category: 'Languages',
      },
      {
        id: 'js-playlist',
        title: 'JavaScript Tutorials for Beginners',
        resourceUrl: 'http://www.youtube.com/playlist?list=PLu71SKxNbfoBuX3f4EOACle2y-tRC5Q37',
        type: 'playlist',
        isFree: true,
        imageId: 'javascript',
        category: 'Languages',
      },
      {
        id: 'react-video',
        title: 'React Tutorial',
        resourceUrl: 'https://youtu.be/vz1RlUyrc3w?si=iM47jMLDs9_n7Brd',
        type: 'video',
        isFree: true,
        imageId: 'react',
        category: 'Languages',
      },
    ],
  },
  {
    name: 'AI Tools',
    courses: [
      {
        id: 'nano-banana',
        title: 'Google Nano Banana',
        resourceUrl: 'https://youtu.be/lfE-csUyPF4?si=vbLAXBODDX2NnFbE',
        type: 'video',
        isFree: true,
        imageId: 'ai-tools',
        category: 'AI Tools',
      },
      {
        id: 'antigravity',
        title: 'Google Antigravity',
        resourceUrl: 'https://youtu.be/EY4eqjdrEew?si=bscW4PT1v8P6a77E',
        type: 'video',
        isFree: true,
        imageId: 'ai-tools',
        category: 'AI Tools',
      },
      {
        id: 'ai-studio',
        title: 'Google AI Studio',
        resourceUrl: 'https://youtu.be/a8NtWQbQI4E?si=jwBv1b_YjdS83fM5',
        type: 'video',
        isFree: true,
        imageId: 'ai-tools',
        category: 'AI Tools',
      },
      {
        id: 'cursor-ai',
        title: 'Cursor AI',
        resourceUrl: 'https://youtu.be/3289vhOUdKA?si=nmnt-0pfv92LzPQ9',
        type: 'video',
        isFree: true,
        imageId: 'ai-tools',
        category: 'AI Tools',
      },
      {
        id: 'gamma-ai',
        title: 'Gamma AI (For PPT)',
        resourceUrl: 'https://youtu.be/KcbXKUR7-a0?si=iMo9tpecte9DP5vq',
        type: 'video',
        isFree: true,
        imageId: 'ai-tools',
        category: 'AI Tools',
      },
    ],
  },
  {
    name: 'Skills',
    courses: [
      {
        id: 'dsa-course',
        title: 'DSA',
        resourceUrl: 'https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2',
        type: 'course',
        isFree: true,
        imageId: 'dsa',
        category: 'Skills',
      },
      {
        id: 'frontend-video',
        title: 'Frontend Development',
        resourceUrl: 'https://www.youtube.com/watch?v=RecyG_U6--M',
        type: 'video',
        isFree: true,
        imageId: 'frontend',
        category: 'Skills',
      },
      {
        id: 'backend-video',
        title: 'Backend Development',
        resourceUrl: 'https://www.youtube.com/watch?v=gxHXPmePnvo',
        type: 'video',
        isFree: true,
        imageId: 'backend',
        category: 'Skills',
      },
      {
        id: 'full-stack-info',
        title: 'Full-Stack Info',
        resourceUrl: 'https://www.youtube.com/watch?v=wS974JC_CoE',
        type: 'info',
        isFree: true,
        imageId: 'full-stack',
        category: 'Skills',
      },
      {
        id: 'ui-ux-info',
        title: 'UI/UX Info',
        resourceUrl: 'https://www.youtube.com/watch?v=55NvZjUZIO8',
        type: 'info',
        isFree: true,
        imageId: 'ui-ux',
        category: 'Skills',
      },
      {
        id: 'ui-ux-video',
        title: 'UI/UX Video Course',
        resourceUrl: 'https://www.youtube.com/watch?v=jwCmIBJ8Jtc',
        type: 'video',
        isFree: true,
        imageId: 'ui-ux',
        category: 'Skills',
      },
      {
        id: 'cloud-video',
        title: 'Cloud Computing',
        resourceUrl: 'https://www.youtube.com/watch?v=2LaAJq1lB1Q',
        type: 'video',
        isFree: true,
        imageId: 'cloud',
        category: 'Skills',
      },
      {
        id: 'ml-video',
        title: 'Machine Learning',
        resourceUrl: 'https://www.youtube.com/watch?v=LvC68w9JS4Y',
        type: 'video',
        isFree: true,
        imageId: 'machine-learning',
        category: 'Skills',
      },
      {
        id: 'blockchain-video',
        title: 'Blockchain',
        resourceUrl: 'https://www.youtube.com/watch?v=jcgfQEbptdo',
        type: 'video',
        isFree: true,
        imageId: 'blockchain',
        category: 'Skills',
      },
      {
        id: 'android-video',
        title: 'Android Development',
        resourceUrl: 'https://www.youtube.com/watch?v=mXjZQX3UzOs',
        type: 'video',
        isFree: true,
        imageId: 'android',
        category: 'Skills',
      },
    ],
  },
  {
    name: 'Other Stuff',
    courses: [
      {
        id: 'linkedin-tips',
        title: 'LinkedIn Profile Tips',
        resourceUrl: 'https://youtu.be/-jf4dCd4sM8?si=Ov0vf5bnvD36XWeK',
        type: 'video',
        isFree: true,
        imageId: 'linkedin',
        category: 'Other Stuff',
      },
      {
        id: 'git-github-tutorial',
        title: 'Git/GitHub Tutorial',
        resourceUrl: 'https://youtu.be/uwyP5SNlQAU?si=Efqktclurw340KbX',
        type: 'video',
        isFree: true,
        imageId: 'github',
        category: 'Other Stuff',
      },
    ],
  },
];
